# Generated by Django 3.2 on 2022-12-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='style_traning',
            field=models.CharField(choices=[('تنافسي', 'تنافسي'), ('تشاركي', 'تشاركي')], default=1, max_length=50, verbose_name='نمط الحشد'),
            preserve_default=False,
        ),
    ]
