# Generated by Django 3.2 on 2022-11-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_skills_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['arrang_post']},
        ),
        migrations.AlterField(
            model_name='post',
            name='skills_category',
            field=models.CharField(choices=[('انتاج ونصميم المقررات الإلكترونية', 'انتاج ونصميم المقررات الإلكترونية'), ('التقويم الإلكتروني عن بعد', 'التقويم الإلكتروني عن بعد'), ('إدارة الفصول الإفتراضية', 'إدارة الفصول الإفتراضية'), ('تطبيقات الحوسبة السحابية', 'تطبيقات الحوسبة السحابية')], max_length=50, verbose_name='skills'),
        ),
    ]
