# Generated by Django 3.2 on 2022-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_arrang_post_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skills_category',
            field=models.CharField(choices=[('IT', 'IT'), ('x', 'xx'), ('y', 'yyy'), ('z', 'zzz')], default=2, max_length=50, verbose_name='skills'),
            preserve_default=False,
        ),
    ]
