# Generated by Django 4.1.7 on 2023-03-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='style_traning',
            field=models.CharField(choices=[('تنافسي', 'تنافسي'), ('تشاركي', 'تشاركي')], max_length=50),
        ),
    ]
