# Generated by Django 3.2 on 2022-12-31 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=15, verbose_name='الاسم')),
                ('Contactus_title', models.CharField(max_length=50, verbose_name='العنوان')),
                ('Contactus_description', models.TextField(max_length=500, verbose_name='- الموضوع')),
                ('Contactus_category', models.CharField(choices=[('انتاج ونصميم المقررات الإلكترونية', 'انتاج ونصميم المقررات الإلكترونية'), ('التقويم الإلكتروني عن بعد', 'التقويم الإلكتروني عن بعد'), ('إدارة الفصول الإفتراضية', 'إدارة الفصول الإفتراضية'), ('تطبيقات الحوسبة السحابية', 'تطبيقات الحوسبة السحابية'), ('بيئة التدريب', 'بيئة التدريب'), ('عام', 'عام')], max_length=50, verbose_name='المجال')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contactus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
