# Generated by Django 3.1.5 on 2021-04-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='author_name',
            field=models.CharField(max_length=15, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='share',
            name='description',
            field=models.TextField(max_length=500, verbose_name='التعليق-الوصف'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_category',
            field=models.CharField(choices=[('IT', 'IT'), ('تربوي', 'تربوي'), ('إداري', 'إداري')], max_length=50, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_title',
            field=models.CharField(max_length=50, verbose_name='العنوان'),
        ),
    ]
