# Generated by Django 3.2 on 2022-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20221128_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='description',
            field=models.TextField(max_length=500, verbose_name='التعليق-حشد المصادر'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_category',
            field=models.CharField(choices=[('انتاج ونصميم المقررات الإلكترونية', 'انتاج ونصميم المقررات الإلكترونية'), ('التقويم الإلكتروني عن بعد', 'التقويم الإلكتروني عن بعد'), ('إدارة الفصول الإفتراضية', 'إدارة الفصول الإفتراضية'), ('تطبيقات الحوسبة السحابية', 'تطبيقات الحوسبة السحابية')], max_length=50, verbose_name='المجال'),
        ),
    ]
